# Generated by Django 5.2.7 on 2025-12-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
